# Generated by Django 5.1.6 on 2025-02-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0003_users1_alter_courses_id_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod_Users',
            fields=[
                ('ID_User', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('ID_Role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_web.roles')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='courses',
            name='ID_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_web.mod_users'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='ID_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_web.mod_users'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='ID_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_web.mod_users'),
        ),
        migrations.DeleteModel(
            name='Users1',
        ),
    ]
