# Generated by Django 5.1.6 on 2025-02-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0004_mod_users_alter_courses_id_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mod_users',
            table='Mod_Users',
        ),
    ]
