# Generated by Django 5.1.6 on 2025-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0006_mod_users_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Roles1',
        ),
    ]
