# Generated by Django 5.1.6 on 2025-02-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0007_rename_roles_roles1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles1',
            new_name='Roles',
        ),
    ]
